server:
  servlet:
    contextPath: /dev
  port: 8888

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  
  jpa:
     database-platform: org.hibernate.dialect.H2Dialect
  h2:
     console:
        enabled: true
  servlet:
     multipart:
        max-file-size: 1024KB
        max-request-size: 1024KB
  http:
     multipart:
        enabled: true