/*CREATE SEQUENCE inventory_seq
START WITH 1
INCREMENT BY 1
CYCLE;

CREATE SEQUENCE product_seq
START WITH 1
INCREMENT BY 1
CYCLE;*/

INSERT INTO USERS (ID,USERNAME,PASSWORD) VALUES (1,
   'saloni','$2y$12$Ax0IluF.ECmR/xg7JRq.f.KubhLP08oqR5TOojn6849cxdoCuB8pa');

INSERT INTO USERS (ID,USERNAME,PASSWORD) VALUES (2,
   'tyagi','$2y$12$y1ID5vg3VtQ4NHNjV7V9IOsSSQXlWKQPnG/sEHJXINjT7/dWgWfpK');